### ISSUE TITLE
The checkfinished endpoint should be execpt from the 503 maintenance logic

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_outage#233]
ie if you are NOT in the ip list, and you hit this check ajax, you should always get the real script and not be intercepted by the outage page itself and get a 503.

**Comment by brendanheywood** [comment]
Needs something like 

```
define('NO_OUTAGE', true);
```

and for the boostrap to detect this

**Comment by yao9394** [comment]
https://github.com/catalyst/moodle-auth_outage/pull/238 
PR attached

**Comment by yao9394** [comment]
Hi @brendanheywood 
Thanks for your help on explaining this issue. It seems the checkfinished ajax call happens when there is warning bar, but maintenance mode blocks that bar as well. I believe there might be somewhere else need to make this call, which I still don't know. Could you please have a look at this PR when you get a chance, and let me know if there is any more change needed to address this issue? 
Thanks,

John Y
