### ISSUE TITLE
Add outage bar to top of window if inside an outage 'warning period' (4 hours)

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_outage#9]
We need to hook into something before the page renders and add the bar at the top if needed. There is no perfect api for this so we need to work around this by using available hooks. We need to make sure it works for:

* [x] the login page
* [x] homepage as guest
* [x] ~~courses page as guest~~
* [x] homepage when logged
* [x] courses page when logged

* [x] the login page itself we can get using the auth loginpage_hook()
* [x] for the others play with using auth_outage_extend_navigation_user() for authenticated pages?? or auth_outage_extend_navigation() auth_outage_extend_navigation_frontpage(). This may not be perfect but just best effort to cover as much as possible
* [x] add unit tests for time logic
* [x] add screen shot to readme of bar and breif blurb

**Comment by roperto** [comment]
I could find any piece of code inside my plugin dir that was called except inside admin area or login.

I tried:
* lib.php
* locallib.php
* auth.php
* settings.php
* version.php

I could not hook the functions:
* `auth_outage_extend_navigation_user()`
* `auth_outage_extend_navigation()`
* `auth_outage_extend_navigation_frontpage()`

because none of the plugin's PHP files were included at all.

If only I can get one of the plugin files to be included or required I can work from there. I was feeling like another type of plugin (or another additional required plugin) could be the way, but I think it's too early to jump into that.

Another issue that I can see is that the auth_outage plugin is not called to check the user's credentials because the authentication method is from another plugin, Moodle does not seem to check auth_outage anymore once the user has authenticated somewhere else. I am not sure how to block the access during an outage.

Cheers

**Comment by roperto** [comment]
I am using the:
* `loginpage_hook()`
* `auth_outage_extend_navigation_user()`
* `auth_outage_extend_navigation_frontpage()`

I set a breakpoint on
* `auth_outage_extend_navigation()` but it was not called at all, maybe an earlier version?

The issue I had was all about cache, as you said.

Cheers,

**Comment by brendanheywood** [comment]
auth_outage_extend_navigation I know is only called for local plugins, the three hooks are using above should be almost all bases covered, at least all the important ones
